package fts.instrumente.listeners;

import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.block.Action;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class CheckKlavierItemListner implements Listener {

    private final List<String> musicItems = new ArrayList<String>(Arrays.asList(
            "§aBass",
            "§aGitarre",
            "§aEisen Xylophon",
            "§aKnochen Xylophon",
            "§aKuhglocke",
            "§aChimes",
            "§aFlöte",
            "§aSchlagzeug",
            "§aGlockenspiel",
            "§aKlavier"));

    @EventHandler
    public void onPlayerHeldItem(PlayerInteractEvent event) {
        Player player = event.getPlayer();
        if (event.getAction() == Action.RIGHT_CLICK_BLOCK) {
            ItemStack item = player.getInventory().getItemInMainHand();
            if(musicItems.contains(item.getItemMeta().getDisplayName())) {
                event.setCancelled(true);
            }
        }
        if (event.getAction() == Action.RIGHT_CLICK_AIR) {
            ItemStack item = player.getInventory().getItemInMainHand();
            if (item.getType() == Material.STONE_SHOVEL &&
                    item.getItemMeta().getDisplayName().contains("Bass")) {
                Inventory BassInv = Bukkit.createInventory(null, 45, "Bass");
                ItemStack G = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta GMeta = G.getItemMeta();
                GMeta.setDisplayName("G");
                G.setItemMeta(GMeta);
                ItemStack GesFis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta GesFisMeta = GesFis.getItemMeta();
                GesFisMeta.setDisplayName("Fis/Ges");
                GesFis.setItemMeta(GesFisMeta);
                ItemStack Gis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta GisMeta = Gis.getItemMeta();
                GisMeta.setDisplayName("Gis/As");
                Gis.setItemMeta(GisMeta);
                ItemStack A = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta AMeta = A.getItemMeta();
                AMeta.setDisplayName("A");
                A.setItemMeta(AMeta);
                ItemStack B = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta BMeta = B.getItemMeta();
                BMeta.setDisplayName("B/Ais");
                B.setItemMeta(BMeta);
                ItemStack H = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta HMeta = H.getItemMeta();
                HMeta.setDisplayName("H");
                H.setItemMeta(HMeta);
                ItemStack C = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta CMeta = C.getItemMeta();
                CMeta.setDisplayName("C");
                C.setItemMeta(CMeta);
                ItemStack Cis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta CisMeta = Cis.getItemMeta();
                CisMeta.setDisplayName("Cis/Des");
                Cis.setItemMeta(CisMeta);
                ItemStack D = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta DMeta = D.getItemMeta();
                DMeta.setDisplayName("D");
                D.setItemMeta(DMeta);
                ItemStack Dis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta DisMeta = Dis.getItemMeta();
                DisMeta.setDisplayName("Dis/Es");
                Dis.setItemMeta(DisMeta);
                ItemStack E = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta EMeta = E.getItemMeta();
                EMeta.setDisplayName("E");
                E.setItemMeta(EMeta);
                ItemStack F = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta FMeta = F.getItemMeta();
                FMeta.setDisplayName("F");
                F.setItemMeta(FMeta);
                ItemStack Fis2 = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta Fis2Meta = Fis2.getItemMeta();
                Fis2Meta.setDisplayName(".Fis/Ges");
                Fis2.setItemMeta(Fis2Meta);
                ItemStack G2 = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta G2Meta = G2.getItemMeta();
                G2Meta.setDisplayName("G");
                G2.setItemMeta(G2Meta);
                BassInv.setItem(16, G2);
                BassInv.setItem(7, Fis2);
                BassInv.setItem(6, F);
                BassInv.setItem(15, F);
                BassInv.setItem(14, E);
                BassInv.setItem(5, Dis);
                BassInv.setItem(13, D);
                BassInv.setItem(4, Cis);
                BassInv.setItem(12, C);
                BassInv.setItem(11, H);
                BassInv.setItem(2, B);
                BassInv.setItem(10, A);
                BassInv.setItem(1, Gis);
                BassInv.setItem(9, G);
                BassInv.setItem(0, GesFis);
                BassInv.setItem(3, C);
                BassInv.setItem(43, G2);
                BassInv.setItem(34, Fis2);
                BassInv.setItem(33, F);
                BassInv.setItem(42, F);
                BassInv.setItem(41, E);
                BassInv.setItem(32, Dis);
                BassInv.setItem(40, D);
                BassInv.setItem(31, Cis);
                BassInv.setItem(39, C);
                BassInv.setItem(38, H);
                BassInv.setItem(29, B);
                BassInv.setItem(37, A);
                BassInv.setItem(28, Gis);
                BassInv.setItem(36, G);
                BassInv.setItem(27, GesFis);
                BassInv.setItem(30, C);
                player.openInventory(BassInv);
            }
            if (item.getType() == Material.WOODEN_SHOVEL &&
                    item.getItemMeta().getDisplayName().contains("Gitarre")) {
                Inventory GitrInv = Bukkit.createInventory(null, 45, "Gitarre");
                ItemStack G = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta GMeta = G.getItemMeta();
                GMeta.setDisplayName("G");
                G.setItemMeta(GMeta);
                ItemStack GesFis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta GesFisMeta = GesFis.getItemMeta();
                GesFisMeta.setDisplayName("Fis/Ges");
                GesFis.setItemMeta(GesFisMeta);
                ItemStack Gis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta GisMeta = Gis.getItemMeta();
                GisMeta.setDisplayName("Gis/As");
                Gis.setItemMeta(GisMeta);
                ItemStack A = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta AMeta = A.getItemMeta();
                AMeta.setDisplayName("A");
                A.setItemMeta(AMeta);
                ItemStack B = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta BMeta = B.getItemMeta();
                BMeta.setDisplayName("B/Ais");
                B.setItemMeta(BMeta);
                ItemStack H = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta HMeta = H.getItemMeta();
                HMeta.setDisplayName("H");
                H.setItemMeta(HMeta);
                ItemStack C = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta CMeta = C.getItemMeta();
                CMeta.setDisplayName("C");
                C.setItemMeta(CMeta);
                ItemStack Cis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta CisMeta = Cis.getItemMeta();
                CisMeta.setDisplayName("Cis/Des");
                Cis.setItemMeta(CisMeta);
                ItemStack D = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta DMeta = D.getItemMeta();
                DMeta.setDisplayName("D");
                D.setItemMeta(DMeta);
                ItemStack Dis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta DisMeta = Dis.getItemMeta();
                DisMeta.setDisplayName("Dis/Es");
                Dis.setItemMeta(DisMeta);
                ItemStack E = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta EMeta = E.getItemMeta();
                EMeta.setDisplayName("E");
                E.setItemMeta(EMeta);
                ItemStack F = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta FMeta = F.getItemMeta();
                FMeta.setDisplayName("F");
                F.setItemMeta(FMeta);
                ItemStack Fis2 = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta Fis2Meta = Fis2.getItemMeta();
                Fis2Meta.setDisplayName(".Fis/Ges");
                Fis2.setItemMeta(Fis2Meta);
                ItemStack G2 = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta G2Meta = G2.getItemMeta();
                G2Meta.setDisplayName("G");
                G2.setItemMeta(G2Meta);
                GitrInv.setItem(16, G2);
                GitrInv.setItem(7, Fis2);
                GitrInv.setItem(6, F);
                GitrInv.setItem(15, F);
                GitrInv.setItem(14, E);
                GitrInv.setItem(5, Dis);
                GitrInv.setItem(13, D);
                GitrInv.setItem(4, Cis);
                GitrInv.setItem(12, C);
                GitrInv.setItem(11, H);
                GitrInv.setItem(2, B);
                GitrInv.setItem(10, A);
                GitrInv.setItem(1, Gis);
                GitrInv.setItem(9, G);
                GitrInv.setItem(0, GesFis);
                GitrInv.setItem(3, C);
                GitrInv.setItem(43, G2);
                GitrInv.setItem(34, Fis2);
                GitrInv.setItem(33, F);
                GitrInv.setItem(42, F);
                GitrInv.setItem(41, E);
                GitrInv.setItem(32, Dis);
                GitrInv.setItem(40, D);
                GitrInv.setItem(31, Cis);
                GitrInv.setItem(39, C);
                GitrInv.setItem(38, H);
                GitrInv.setItem(29, B);
                GitrInv.setItem(37, A);
                GitrInv.setItem(28, Gis);
                GitrInv.setItem(36, G);
                GitrInv.setItem(27, GesFis);
                GitrInv.setItem(30, C);
                player.openInventory(GitrInv);
            }
            if (item.getType() == Material.ACTIVATOR_RAIL &&
                    item.getItemMeta().getDisplayName().contains("Eisen Xylophon")) {
                Inventory XyloPIInv = Bukkit.createInventory(null, 45, "Eisen Xylophon");
                ItemStack G = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta GMeta = G.getItemMeta();
                GMeta.setDisplayName("G");
                G.setItemMeta(GMeta);
                ItemStack GesFis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta GesFisMeta = GesFis.getItemMeta();
                GesFisMeta.setDisplayName("Fis/Ges");
                GesFis.setItemMeta(GesFisMeta);
                ItemStack Gis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta GisMeta = Gis.getItemMeta();
                GisMeta.setDisplayName("Gis/As");
                Gis.setItemMeta(GisMeta);
                ItemStack A = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta AMeta = A.getItemMeta();
                AMeta.setDisplayName("A");
                A.setItemMeta(AMeta);
                ItemStack B = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta BMeta = B.getItemMeta();
                BMeta.setDisplayName("B/Ais");
                B.setItemMeta(BMeta);
                ItemStack H = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta HMeta = H.getItemMeta();
                HMeta.setDisplayName("H");
                H.setItemMeta(HMeta);
                ItemStack C = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta CMeta = C.getItemMeta();
                CMeta.setDisplayName("C");
                C.setItemMeta(CMeta);
                ItemStack Cis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta CisMeta = Cis.getItemMeta();
                CisMeta.setDisplayName("Cis/Des");
                Cis.setItemMeta(CisMeta);
                ItemStack D = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta DMeta = D.getItemMeta();
                DMeta.setDisplayName("D");
                D.setItemMeta(DMeta);
                ItemStack Dis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta DisMeta = Dis.getItemMeta();
                DisMeta.setDisplayName("Dis/Es");
                Dis.setItemMeta(DisMeta);
                ItemStack E = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta EMeta = E.getItemMeta();
                EMeta.setDisplayName("E");
                E.setItemMeta(EMeta);
                ItemStack F = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta FMeta = F.getItemMeta();
                FMeta.setDisplayName("F");
                F.setItemMeta(FMeta);
                ItemStack Fis2 = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta Fis2Meta = Fis2.getItemMeta();
                Fis2Meta.setDisplayName(".Fis/Ges");
                Fis2.setItemMeta(Fis2Meta);
                ItemStack G2 = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta G2Meta = G2.getItemMeta();
                G2Meta.setDisplayName("G");
                G2.setItemMeta(G2Meta);
                XyloPIInv.setItem(16, G2);
                XyloPIInv.setItem(7, Fis2);
                XyloPIInv.setItem(6, F);
                XyloPIInv.setItem(15, F);
                XyloPIInv.setItem(14, E);
                XyloPIInv.setItem(5, Dis);
                XyloPIInv.setItem(13, D);
                XyloPIInv.setItem(4, Cis);
                XyloPIInv.setItem(12, C);
                XyloPIInv.setItem(11, H);
                XyloPIInv.setItem(2, B);
                XyloPIInv.setItem(10, A);
                XyloPIInv.setItem(1, Gis);
                XyloPIInv.setItem(9, G);
                XyloPIInv.setItem(0, GesFis);
                XyloPIInv.setItem(3, C);
                XyloPIInv.setItem(43, G2);
                XyloPIInv.setItem(34, Fis2);
                XyloPIInv.setItem(33, F);
                XyloPIInv.setItem(42, F);
                XyloPIInv.setItem(41, E);
                XyloPIInv.setItem(32, Dis);
                XyloPIInv.setItem(40, D);
                XyloPIInv.setItem(31, Cis);
                XyloPIInv.setItem(39, C);
                XyloPIInv.setItem(38, H);
                XyloPIInv.setItem(29, B);
                XyloPIInv.setItem(37, A);
                XyloPIInv.setItem(28, Gis);
                XyloPIInv.setItem(36, G);
                XyloPIInv.setItem(27, GesFis);
                XyloPIInv.setItem(30, C);
                player.openInventory(XyloPIInv);
            }
            if (item.getType() == Material.RAIL &&
                    item.getItemMeta().getDisplayName().contains("Knochen Xylophon")) {
                Inventory XyloPBInv = Bukkit.createInventory(null, 45, "Knochen Xylophon");
                ItemStack G = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta GMeta = G.getItemMeta();
                GMeta.setDisplayName("G");
                G.setItemMeta(GMeta);
                ItemStack GesFis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta GesFisMeta = GesFis.getItemMeta();
                GesFisMeta.setDisplayName("Fis/Ges");
                GesFis.setItemMeta(GesFisMeta);
                ItemStack Gis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta GisMeta = Gis.getItemMeta();
                GisMeta.setDisplayName("Gis/As");
                Gis.setItemMeta(GisMeta);
                ItemStack A = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta AMeta = A.getItemMeta();
                AMeta.setDisplayName("A");
                A.setItemMeta(AMeta);
                ItemStack B = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta BMeta = B.getItemMeta();
                BMeta.setDisplayName("B/Ais");
                B.setItemMeta(BMeta);
                ItemStack H = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta HMeta = H.getItemMeta();
                HMeta.setDisplayName("H");
                H.setItemMeta(HMeta);
                ItemStack C = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta CMeta = C.getItemMeta();
                CMeta.setDisplayName("C");
                C.setItemMeta(CMeta);
                ItemStack Cis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta CisMeta = Cis.getItemMeta();
                CisMeta.setDisplayName("Cis/Des");
                Cis.setItemMeta(CisMeta);
                ItemStack D = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta DMeta = D.getItemMeta();
                DMeta.setDisplayName("D");
                D.setItemMeta(DMeta);
                ItemStack Dis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta DisMeta = Dis.getItemMeta();
                DisMeta.setDisplayName("Dis/Es");
                Dis.setItemMeta(DisMeta);
                ItemStack E = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta EMeta = E.getItemMeta();
                EMeta.setDisplayName("E");
                E.setItemMeta(EMeta);
                ItemStack F = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta FMeta = F.getItemMeta();
                FMeta.setDisplayName("F");
                F.setItemMeta(FMeta);
                ItemStack Fis2 = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta Fis2Meta = Fis2.getItemMeta();
                Fis2Meta.setDisplayName(".Fis/Ges");
                Fis2.setItemMeta(Fis2Meta);
                ItemStack G2 = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta G2Meta = G2.getItemMeta();
                G2Meta.setDisplayName("G");
                G2.setItemMeta(G2Meta);
                XyloPBInv.setItem(16, G2);
                XyloPBInv.setItem(7, Fis2);
                XyloPBInv.setItem(6, F);
                XyloPBInv.setItem(15, F);
                XyloPBInv.setItem(14, E);
                XyloPBInv.setItem(5, Dis);
                XyloPBInv.setItem(13, D);
                XyloPBInv.setItem(4, Cis);
                XyloPBInv.setItem(12, C);
                XyloPBInv.setItem(11, H);
                XyloPBInv.setItem(2, B);
                XyloPBInv.setItem(10, A);
                XyloPBInv.setItem(1, Gis);
                XyloPBInv.setItem(9, G);
                XyloPBInv.setItem(0, GesFis);
                XyloPBInv.setItem(3, C);
                XyloPBInv.setItem(43, G2);
                XyloPBInv.setItem(34, Fis2);
                XyloPBInv.setItem(33, F);
                XyloPBInv.setItem(42, F);
                XyloPBInv.setItem(41, E);
                XyloPBInv.setItem(32, Dis);
                XyloPBInv.setItem(40, D);
                XyloPBInv.setItem(31, Cis);
                XyloPBInv.setItem(39, C);
                XyloPBInv.setItem(38, H);
                XyloPBInv.setItem(29, B);
                XyloPBInv.setItem(37, A);
                XyloPBInv.setItem(28, Gis);
                XyloPBInv.setItem(36, G);
                XyloPBInv.setItem(27, GesFis);
                XyloPBInv.setItem(30, C);
                player.openInventory(XyloPBInv);
            }
            if (item.getType() == Material.BELL &&
                    item.getItemMeta().getDisplayName().contains("Kuhglocke")) {
                Inventory KuhGInv = Bukkit.createInventory(null, 45, "Kuhglocke");
                ItemStack G = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta GMeta = G.getItemMeta();
                GMeta.setDisplayName("G");
                G.setItemMeta(GMeta);
                ItemStack GesFis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta GesFisMeta = GesFis.getItemMeta();
                GesFisMeta.setDisplayName("Fis/Ges");
                GesFis.setItemMeta(GesFisMeta);
                ItemStack Gis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta GisMeta = Gis.getItemMeta();
                GisMeta.setDisplayName("Gis/As");
                Gis.setItemMeta(GisMeta);
                ItemStack A = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta AMeta = A.getItemMeta();
                AMeta.setDisplayName("A");
                A.setItemMeta(AMeta);
                ItemStack B = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta BMeta = B.getItemMeta();
                BMeta.setDisplayName("B/Ais");
                B.setItemMeta(BMeta);
                ItemStack H = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta HMeta = H.getItemMeta();
                HMeta.setDisplayName("H");
                H.setItemMeta(HMeta);
                ItemStack C = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta CMeta = C.getItemMeta();
                CMeta.setDisplayName("C");
                C.setItemMeta(CMeta);
                ItemStack Cis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta CisMeta = Cis.getItemMeta();
                CisMeta.setDisplayName("Cis/Des");
                Cis.setItemMeta(CisMeta);
                ItemStack D = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta DMeta = D.getItemMeta();
                DMeta.setDisplayName("D");
                D.setItemMeta(DMeta);
                ItemStack Dis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta DisMeta = Dis.getItemMeta();
                DisMeta.setDisplayName("Dis/Es");
                Dis.setItemMeta(DisMeta);
                ItemStack E = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta EMeta = E.getItemMeta();
                EMeta.setDisplayName("E");
                E.setItemMeta(EMeta);
                ItemStack F = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta FMeta = F.getItemMeta();
                FMeta.setDisplayName("F");
                F.setItemMeta(FMeta);
                ItemStack Fis2 = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta Fis2Meta = Fis2.getItemMeta();
                Fis2Meta.setDisplayName(".Fis/Ges");
                Fis2.setItemMeta(Fis2Meta);
                ItemStack G2 = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta G2Meta = G2.getItemMeta();
                G2Meta.setDisplayName("G");
                G2.setItemMeta(G2Meta);
                KuhGInv.setItem(16, G2);
                KuhGInv.setItem(7, Fis2);
                KuhGInv.setItem(6, F);
                KuhGInv.setItem(15, F);
                KuhGInv.setItem(14, E);
                KuhGInv.setItem(5, Dis);
                KuhGInv.setItem(13, D);
                KuhGInv.setItem(4, Cis);
                KuhGInv.setItem(12, C);
                KuhGInv.setItem(11, H);
                KuhGInv.setItem(2, B);
                KuhGInv.setItem(10, A);
                KuhGInv.setItem(1, Gis);
                KuhGInv.setItem(9, G);
                KuhGInv.setItem(0, GesFis);
                KuhGInv.setItem(3, C);
                KuhGInv.setItem(43, G2);
                KuhGInv.setItem(34, Fis2);
                KuhGInv.setItem(33, F);
                KuhGInv.setItem(42, F);
                KuhGInv.setItem(41, E);
                KuhGInv.setItem(32, Dis);
                KuhGInv.setItem(40, D);
                KuhGInv.setItem(31, Cis);
                KuhGInv.setItem(39, C);
                KuhGInv.setItem(38, H);
                KuhGInv.setItem(29, B);
                KuhGInv.setItem(37, A);
                KuhGInv.setItem(28, Gis);
                KuhGInv.setItem(36, G);
                KuhGInv.setItem(27, GesFis);
                KuhGInv.setItem(30, C);
                player.openInventory(KuhGInv);
            }
            if (item.getType() == Material.IRON_BARS &&
                    item.getItemMeta().getDisplayName().contains("Chimes")) {
                Inventory ChimInv = Bukkit.createInventory(null, 45, "Chimes");
                ItemStack G = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta GMeta = G.getItemMeta();
                GMeta.setDisplayName("G");
                G.setItemMeta(GMeta);
                ItemStack GesFis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta GesFisMeta = GesFis.getItemMeta();
                GesFisMeta.setDisplayName("Fis/Ges");
                GesFis.setItemMeta(GesFisMeta);
                ItemStack Gis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta GisMeta = Gis.getItemMeta();
                GisMeta.setDisplayName("Gis/As");
                Gis.setItemMeta(GisMeta);
                ItemStack A = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta AMeta = A.getItemMeta();
                AMeta.setDisplayName("A");
                A.setItemMeta(AMeta);
                ItemStack B = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta BMeta = B.getItemMeta();
                BMeta.setDisplayName("B/Ais");
                B.setItemMeta(BMeta);
                ItemStack H = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta HMeta = H.getItemMeta();
                HMeta.setDisplayName("H");
                H.setItemMeta(HMeta);
                ItemStack C = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta CMeta = C.getItemMeta();
                CMeta.setDisplayName("C");
                C.setItemMeta(CMeta);
                ItemStack Cis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta CisMeta = Cis.getItemMeta();
                CisMeta.setDisplayName("Cis/Des");
                Cis.setItemMeta(CisMeta);
                ItemStack D = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta DMeta = D.getItemMeta();
                DMeta.setDisplayName("D");
                D.setItemMeta(DMeta);
                ItemStack Dis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta DisMeta = Dis.getItemMeta();
                DisMeta.setDisplayName("Dis/Es");
                Dis.setItemMeta(DisMeta);
                ItemStack E = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta EMeta = E.getItemMeta();
                EMeta.setDisplayName("E");
                E.setItemMeta(EMeta);
                ItemStack F = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta FMeta = F.getItemMeta();
                FMeta.setDisplayName("F");
                F.setItemMeta(FMeta);
                ItemStack Fis2 = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta Fis2Meta = Fis2.getItemMeta();
                Fis2Meta.setDisplayName(".Fis/Ges");
                Fis2.setItemMeta(Fis2Meta);
                ItemStack G2 = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta G2Meta = G2.getItemMeta();
                G2Meta.setDisplayName("G");
                G2.setItemMeta(G2Meta);
                ChimInv.setItem(16, G2);
                ChimInv.setItem(7, Fis2);
                ChimInv.setItem(6, F);
                ChimInv.setItem(15, F);
                ChimInv.setItem(14, E);
                ChimInv.setItem(5, Dis);
                ChimInv.setItem(13, D);
                ChimInv.setItem(4, Cis);
                ChimInv.setItem(12, C);
                ChimInv.setItem(11, H);
                ChimInv.setItem(2, B);
                ChimInv.setItem(10, A);
                ChimInv.setItem(1, Gis);
                ChimInv.setItem(9, G);
                ChimInv.setItem(0, GesFis);
                ChimInv.setItem(3, C);
                ChimInv.setItem(43, G2);
                ChimInv.setItem(34, Fis2);
                ChimInv.setItem(33, F);
                ChimInv.setItem(42, F);
                ChimInv.setItem(41, E);
                ChimInv.setItem(32, Dis);
                ChimInv.setItem(40, D);
                ChimInv.setItem(31, Cis);
                ChimInv.setItem(39, C);
                ChimInv.setItem(38, H);
                ChimInv.setItem(29, B);
                ChimInv.setItem(37, A);
                ChimInv.setItem(28, Gis);
                ChimInv.setItem(36, G);
                ChimInv.setItem(27, GesFis);
                ChimInv.setItem(30, C);
                player.openInventory(ChimInv);
            }
            if (item.getType() == Material.STICK &&
                    item.getItemMeta().getDisplayName().contains("Flöte")) {
                Inventory FltInv = Bukkit.createInventory(null, 45, "Flöte");
                ItemStack G = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta GMeta = G.getItemMeta();
                GMeta.setDisplayName("G");
                G.setItemMeta(GMeta);
                ItemStack GesFis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta GesFisMeta = GesFis.getItemMeta();
                GesFisMeta.setDisplayName("Fis/Ges");
                GesFis.setItemMeta(GesFisMeta);
                ItemStack Gis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta GisMeta = Gis.getItemMeta();
                GisMeta.setDisplayName("Gis/As");
                Gis.setItemMeta(GisMeta);
                ItemStack A = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta AMeta = A.getItemMeta();
                AMeta.setDisplayName("A");
                A.setItemMeta(AMeta);
                ItemStack B = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta BMeta = B.getItemMeta();
                BMeta.setDisplayName("B/Ais");
                B.setItemMeta(BMeta);
                ItemStack H = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta HMeta = H.getItemMeta();
                HMeta.setDisplayName("H");
                H.setItemMeta(HMeta);
                ItemStack C = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta CMeta = C.getItemMeta();
                CMeta.setDisplayName("C");
                C.setItemMeta(CMeta);
                ItemStack Cis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta CisMeta = Cis.getItemMeta();
                CisMeta.setDisplayName("Cis/Des");
                Cis.setItemMeta(CisMeta);
                ItemStack D = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta DMeta = D.getItemMeta();
                DMeta.setDisplayName("D");
                D.setItemMeta(DMeta);
                ItemStack Dis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta DisMeta = Dis.getItemMeta();
                DisMeta.setDisplayName("Dis/Es");
                Dis.setItemMeta(DisMeta);
                ItemStack E = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta EMeta = E.getItemMeta();
                EMeta.setDisplayName("E");
                E.setItemMeta(EMeta);
                ItemStack F = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta FMeta = F.getItemMeta();
                FMeta.setDisplayName("F");
                F.setItemMeta(FMeta);
                ItemStack Fis2 = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta Fis2Meta = Fis2.getItemMeta();
                Fis2Meta.setDisplayName(".Fis/Ges");
                Fis2.setItemMeta(Fis2Meta);
                ItemStack G2 = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta G2Meta = G2.getItemMeta();
                G2Meta.setDisplayName("G");
                G2.setItemMeta(G2Meta);
                FltInv.setItem(16, G2);
                FltInv.setItem(7, Fis2);
                FltInv.setItem(6, F);
                FltInv.setItem(15, F);
                FltInv.setItem(14, E);
                FltInv.setItem(5, Dis);
                FltInv.setItem(13, D);
                FltInv.setItem(4, Cis);
                FltInv.setItem(12, C);
                FltInv.setItem(11, H);
                FltInv.setItem(2, B);
                FltInv.setItem(10, A);
                FltInv.setItem(1, Gis);
                FltInv.setItem(9, G);
                FltInv.setItem(0, GesFis);
                FltInv.setItem(3, C);
                FltInv.setItem(43, G2);
                FltInv.setItem(34, Fis2);
                FltInv.setItem(33, F);
                FltInv.setItem(42, F);
                FltInv.setItem(41, E);
                FltInv.setItem(32, Dis);
                FltInv.setItem(40, D);
                FltInv.setItem(31, Cis);
                FltInv.setItem(39, C);
                FltInv.setItem(38, H);
                FltInv.setItem(29, B);
                FltInv.setItem(37, A);
                FltInv.setItem(28, Gis);
                FltInv.setItem(36, G);
                FltInv.setItem(27, GesFis);
                FltInv.setItem(30, C);
                player.openInventory(FltInv);
            }
            if (item.getType() == Material.BARREL &&
                    item.getItemMeta().getDisplayName().contains("Schlagzeug")) {
                Inventory SchlagZInventory = Bukkit.createInventory(null, 27, "Schlagzeug");
                ItemStack stein = new ItemStack(Material.STONE);
                ItemMeta steinM = stein.getItemMeta();
                steinM.setDisplayName("Kick");
                stein.setItemMeta(steinM);
                ItemStack glass = new ItemStack(Material.GLASS);
                ItemMeta glassM = glass.getItemMeta();
                glassM.setDisplayName("Click/Stick");
                glass.setItemMeta(glassM);
                ItemStack sand = new ItemStack(Material.SAND);
                ItemMeta sandM = sand.getItemMeta();
                sandM.setDisplayName("Snare");
                sand.setItemMeta(sandM);
                SchlagZInventory.setItem(2, stein);
                SchlagZInventory.setItem(4, glass);
                SchlagZInventory.setItem(6, sand);
                SchlagZInventory.setItem(11, stein);
                SchlagZInventory.setItem(13, glass);
                SchlagZInventory.setItem(15, sand);
                SchlagZInventory.setItem(20, stein);
                SchlagZInventory.setItem(22, glass);
                SchlagZInventory.setItem(24, sand);
                player.openInventory(SchlagZInventory);
            }
            if (item.getType() == Material.MUSIC_DISC_13 &&
                    item.getItemMeta().getDisplayName().contains("Glockenspiel")) {
                Inventory GlockenSinventory = Bukkit.createInventory(null, 45, "Glockenspiel");
                ItemStack G = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta GMeta = G.getItemMeta();
                GMeta.setDisplayName("G");
                G.setItemMeta(GMeta);
                ItemStack GesFis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta GesFisMeta = GesFis.getItemMeta();
                GesFisMeta.setDisplayName("Fis/Ges");
                GesFis.setItemMeta(GesFisMeta);
                ItemStack Gis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta GisMeta = Gis.getItemMeta();
                GisMeta.setDisplayName("Gis/As");
                Gis.setItemMeta(GisMeta);
                ItemStack A = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta AMeta = A.getItemMeta();
                AMeta.setDisplayName("A");
                A.setItemMeta(AMeta);
                ItemStack B = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta BMeta = B.getItemMeta();
                BMeta.setDisplayName("B/Ais");
                B.setItemMeta(BMeta);
                ItemStack H = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta HMeta = H.getItemMeta();
                HMeta.setDisplayName("H");
                H.setItemMeta(HMeta);
                ItemStack C = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta CMeta = C.getItemMeta();
                CMeta.setDisplayName("C");
                C.setItemMeta(CMeta);
                ItemStack Cis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta CisMeta = Cis.getItemMeta();
                CisMeta.setDisplayName("Cis/Des");
                Cis.setItemMeta(CisMeta);
                ItemStack D = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta DMeta = D.getItemMeta();
                DMeta.setDisplayName("D");
                D.setItemMeta(DMeta);
                ItemStack Dis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta DisMeta = Dis.getItemMeta();
                DisMeta.setDisplayName("Dis/Es");
                Dis.setItemMeta(DisMeta);
                ItemStack E = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta EMeta = E.getItemMeta();
                EMeta.setDisplayName("E");
                E.setItemMeta(EMeta);
                ItemStack F = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta FMeta = F.getItemMeta();
                FMeta.setDisplayName("F");
                F.setItemMeta(FMeta);
                ItemStack Fis2 = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta Fis2Meta = Fis2.getItemMeta();
                Fis2Meta.setDisplayName(".Fis/Ges");
                Fis2.setItemMeta(Fis2Meta);
                ItemStack G2 = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta G2Meta = G2.getItemMeta();
                G2Meta.setDisplayName("G");
                G2.setItemMeta(G2Meta);
                GlockenSinventory.setItem(16, G2);
                GlockenSinventory.setItem(7, Fis2);
                GlockenSinventory.setItem(6, F);
                GlockenSinventory.setItem(15, F);
                GlockenSinventory.setItem(14, E);
                GlockenSinventory.setItem(5, Dis);
                GlockenSinventory.setItem(13, D);
                GlockenSinventory.setItem(4, Cis);
                GlockenSinventory.setItem(12, C);
                GlockenSinventory.setItem(11, H);
                GlockenSinventory.setItem(2, B);
                GlockenSinventory.setItem(10, A);
                GlockenSinventory.setItem(1, Gis);
                GlockenSinventory.setItem(9, G);
                GlockenSinventory.setItem(0, GesFis);
                GlockenSinventory.setItem(3, C);
                GlockenSinventory.setItem(43, G2);
                GlockenSinventory.setItem(34, Fis2);
                GlockenSinventory.setItem(33, F);
                GlockenSinventory.setItem(42, F);
                GlockenSinventory.setItem(41, E);
                GlockenSinventory.setItem(32, Dis);
                GlockenSinventory.setItem(40, D);
                GlockenSinventory.setItem(31, Cis);
                GlockenSinventory.setItem(39, C);
                GlockenSinventory.setItem(38, H);
                GlockenSinventory.setItem(29, B);
                GlockenSinventory.setItem(37, A);
                GlockenSinventory.setItem(28, Gis);
                GlockenSinventory.setItem(36, G);
                GlockenSinventory.setItem(27, GesFis);
                GlockenSinventory.setItem(30, C);
                player.openInventory(GlockenSinventory);
            }
            if (item.getType() == Material.MUSIC_DISC_STAL &&
                    item.getItemMeta().getDisplayName().contains("Klavier")) {
                Inventory inventory = Bukkit.createInventory(null, 45, "Klavier");
                ItemStack G = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta GMeta = G.getItemMeta();
                GMeta.setDisplayName("G");
                G.setItemMeta(GMeta);
                ItemStack GesFis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta GesFisMeta = GesFis.getItemMeta();
                GesFisMeta.setDisplayName("Fis/Ges");
                GesFis.setItemMeta(GesFisMeta);
                ItemStack Gis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta GisMeta = Gis.getItemMeta();
                GisMeta.setDisplayName("Gis/As");
                Gis.setItemMeta(GisMeta);
                ItemStack A = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta AMeta = A.getItemMeta();
                AMeta.setDisplayName("A");
                A.setItemMeta(AMeta);
                ItemStack B = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta BMeta = B.getItemMeta();
                BMeta.setDisplayName("B/Ais");
                B.setItemMeta(BMeta);
                ItemStack H = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta HMeta = H.getItemMeta();
                HMeta.setDisplayName("H");
                H.setItemMeta(HMeta);
                ItemStack C = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta CMeta = C.getItemMeta();
                CMeta.setDisplayName("C");
                C.setItemMeta(CMeta);
                ItemStack Cis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta CisMeta = Cis.getItemMeta();
                CisMeta.setDisplayName("Cis/Des");
                Cis.setItemMeta(CisMeta);
                ItemStack D = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta DMeta = D.getItemMeta();
                DMeta.setDisplayName("D");
                D.setItemMeta(DMeta);
                ItemStack Dis = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta DisMeta = Dis.getItemMeta();
                DisMeta.setDisplayName("Dis/Es");
                Dis.setItemMeta(DisMeta);
                ItemStack E = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta EMeta = E.getItemMeta();
                EMeta.setDisplayName("E");
                E.setItemMeta(EMeta);
                ItemStack F = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta FMeta = F.getItemMeta();
                FMeta.setDisplayName("F");
                F.setItemMeta(FMeta);
                ItemStack Fis2 = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
                ItemMeta Fis2Meta = Fis2.getItemMeta();
                Fis2Meta.setDisplayName(".Fis/Ges");
                Fis2.setItemMeta(Fis2Meta);
                ItemStack G2 = new ItemStack(Material.WHITE_STAINED_GLASS_PANE);
                ItemMeta G2Meta = G2.getItemMeta();
                G2Meta.setDisplayName("G");
                G2.setItemMeta(G2Meta);
                inventory.setItem(16, G2);
                inventory.setItem(7, Fis2);
                inventory.setItem(6, F);
                inventory.setItem(15, F);
                inventory.setItem(14, E);
                inventory.setItem(5, Dis);
                inventory.setItem(13, D);
                inventory.setItem(4, Cis);
                inventory.setItem(12, C);
                inventory.setItem(11, H);
                inventory.setItem(2, B);
                inventory.setItem(10, A);
                inventory.setItem(1, Gis);
                inventory.setItem(9, G);
                inventory.setItem(0, GesFis);
                inventory.setItem(3, C);
                inventory.setItem(43, G2);
                inventory.setItem(34, Fis2);
                inventory.setItem(33, F);
                inventory.setItem(42, F);
                inventory.setItem(41, E);
                inventory.setItem(32, Dis);
                inventory.setItem(40, D);
                inventory.setItem(31, Cis);
                inventory.setItem(39, C);
                inventory.setItem(38, H);
                inventory.setItem(29, B);
                inventory.setItem(37, A);
                inventory.setItem(28, Gis);
                inventory.setItem(36, G);
                inventory.setItem(27, GesFis);
                inventory.setItem(30, C);
                player.openInventory(inventory);
                player.openInventory(inventory);
            }
        }
    }
}